version: "3"


services:
  postgresdb:
    env_file:
      - ./project/.env
    build:
      context: ./docker/postgres
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    restart: always
    env_file:
      - ./project/.env
    volumes: 
      - ./project:/project
    build:
      context: ./project
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - postgresdb

  microservice:
    restart: always
    env_file:
      - ./microservice/.env
    volumes: 
      - ./microservice:/microservice
    build:
      context: ./microservice
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    depends_on:
      - postgresdb
      - web

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - postgresdb
      - web
    ports:
      - "80:80"
      - "5001:5001"
    volumes:
      - ./project/static/:/static
      - ./project/media/:/media

